### ISSUE TITLE
parsing password missing

### ISSUE THREAD

**Issue by SchermannR** [smartninja/wd1-py3-exercises#1]
Imho you forgot to parse the passwort within the constructor (__init__)
def __init__(self, name, email, secret_number, **kwargs): -->
def __init__(self, name, email, secret_number, **password**, **kwargs):

**Comment by ramuta** [comment]
Hi! `**kwargs` actually allow for passing additional (custom) parameters to the constructor.

Let's take a look at the whole code for a better context:

```python
from smartninja_nosql.odm import Model


class User(Model):
    def __init__(self, name, email, secret_number, **kwargs):
        self.name = name
        self.email = email
        self.secret_number = secret_number

        super().__init__(**kwargs)
```

As you can see, the additional parameters hidden in `**kwargs` are passed to the parent class called `Model`. The constructor in this class then handles `**kwargs` like this:

```python
class Model:
    def __init__(self, **kwargs):
        for key, value in kwargs.items():
            setattr(self, key, value)
```

You can see this for yourself [here](https://github.com/smartninja/smartninja-nosql/blob/master/smartninja_nosql/odm.py). ;) 

That's why password does not have to be explicitly mentioned in the User model.
